// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using XcluadeAgent.Infrastructure.Persistence;

#nullable enable

namespace XcluadeAgent.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("XcluadeAgent.Core.Models.AuditLog", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<Guid?>("EntityId").HasColumnType("TEXT");
                b.Property<string>("EntityType").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("IpAddress").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("NewValue").HasColumnType("TEXT");
                b.Property<string>("OldValue").HasColumnType("TEXT");
                b.Property<string>("UserAgent").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<Guid?>("UserId").HasColumnType("TEXT");
                b.Property<string>("Username").HasMaxLength(50).HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("Action");
                b.HasIndex("CreatedAt");
                b.HasIndex("EntityType");
                b.HasIndex("UserId");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("XcluadeAgent.Core.Models.Project", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<bool>("AutoDetectFramework").HasColumnType("INTEGER");
                b.Property<string>("Branch").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<bool>("Enabled").HasColumnType("INTEGER");
                b.Property<string>("Environment").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<int>("Framework").HasColumnType("INTEGER");
                b.Property<string>("LastError").HasMaxLength(5000).HasColumnType("TEXT");
                b.Property<DateTime?>("LastSyncAt").HasColumnType("TEXT");
                b.Property<string>("LastSyncedVersion").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("LocalPath").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("ReleaseTagPattern").HasColumnType("TEXT");
                b.Property<string>("Repository").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<int>("Status").HasColumnType("INTEGER");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.Property<bool>("UseReleases").HasColumnType("INTEGER");
                b.Property<string>("WebhookSecret").HasMaxLength(100).HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("Enabled");
                b.HasIndex("Name").IsUnique();
                b.HasIndex("Repository");
                b.HasIndex("Status");

                b.ToTable("Projects");

                b.OwnsOne("XcluadeAgent.Core.Models.ProjectConfig", "Config", b1 =>
                {
                    b1.Property<Guid>("ProjectId").HasColumnType("TEXT");
                    b1.ToJson();
                    b1.WithOwner().HasForeignKey("ProjectId");
                });

                b.Navigation("Config").IsRequired();
            });

            modelBuilder.Entity("XcluadeAgent.Core.Models.SyncHistory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<string>("BackupPath").HasMaxLength(1000).HasColumnType("TEXT");
                b.Property<long>("BytesTransferred").HasColumnType("INTEGER");
                b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                b.Property<long?>("DurationMs").HasColumnType("INTEGER");
                b.Property<string>("ErrorMessage").HasMaxLength(5000).HasColumnType("TEXT");
                b.Property<int>("FilesChanged").HasColumnType("INTEGER");
                b.Property<string>("FromVersion").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("InitiatedBy").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<bool>("IsRollback").HasColumnType("INTEGER");
                b.Property<Guid>("ProjectId").HasColumnType("TEXT");
                b.Property<string>("ProjectName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<Guid?>("RollbackFromId").HasColumnType("TEXT");
                b.Property<DateTime>("StartedAt").HasColumnType("TEXT");
                b.Property<bool>("Success").HasColumnType("INTEGER");
                b.Property<string>("ToVersion").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<int>("Trigger").HasColumnType("INTEGER");

                b.HasKey("Id");
                b.HasIndex("ProjectId");
                b.HasIndex("StartedAt");
                b.HasIndex("Success");
                b.HasIndex("ProjectId", "StartedAt");

                b.ToTable("SyncHistories");
            });

            modelBuilder.Entity("XcluadeAgent.Core.Models.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("DisplayName").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
                b.Property<int>("FailedLoginAttempts").HasColumnType("INTEGER");
                b.Property<string>("GitHubId").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("GitHubUsername").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("TEXT");
                b.Property<string>("LastLoginIp").HasMaxLength(50).HasColumnType("TEXT");
                b.Property<DateTime?>("LockedUntil").HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
                b.Property<int>("Role").HasColumnType("INTEGER");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");
                b.Property<string>("TwoFactorSecret").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("GitHubId");
                b.HasIndex("Username").IsUnique();

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
