#!/bin/bash
# XcluadeAgent Installation Script for Ubuntu/Debian
# Developed by xman studio | https://xman4289.com

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="/opt/xcluadeagent"
SERVICE_NAME="xcluadeagent"
SERVICE_USER="xcluade"
DEFAULT_PORT=5000

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║     ██╗  ██╗ ██████╗██╗     ██╗   ██╗ █████╗ ██████╗ ███████╗     ║"
echo "║     ╚██╗██╔╝██╔════╝██║     ██║   ██║██╔══██╗██╔══██╗██╔════╝     ║"
echo "║      ╚███╔╝ ██║     ██║     ██║   ██║███████║██║  ██║█████╗       ║"
echo "║      ██╔██╗ ██║     ██║     ██║   ██║██╔══██║██║  ██║██╔══╝       ║"
echo "║     ██╔╝ ██╗╚██████╗███████╗╚██████╔╝██║  ██║██████╔╝███████╗     ║"
echo "║     ╚═╝  ╚═╝ ╚═════╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═════╝ ╚══════╝     ║"
echo "║                         AGENT                                      ║"
echo "║                                                                    ║"
echo "║     Installer v1.0.0                                               ║"
echo "║     Developed by: xman studio                                      ║"
echo "║     Website: https://xman4289.com                                  ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root (sudo)${NC}"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    VERSION=$VERSION_ID
else
    echo -e "${RED}Cannot detect operating system${NC}"
    exit 1
fi

echo -e "${GREEN}Detected: $OS $VERSION${NC}"

# Interactive configuration
echo ""
echo -e "${YELLOW}=== Configuration ===${NC}"
echo ""

# Port
read -p "Dashboard port [${DEFAULT_PORT}]: " PORT
PORT=${PORT:-$DEFAULT_PORT}

# Domain
read -p "Domain for dashboard (optional, e.g., sync.yourdomain.com): " DOMAIN

# GitHub Token
read -p "GitHub Personal Access Token: " GITHUB_TOKEN

# SSL
if [ -n "$DOMAIN" ]; then
    read -p "Setup SSL with Let's Encrypt? [y/N]: " SETUP_SSL
    SETUP_SSL=${SETUP_SSL:-n}
fi

# Generate JWT Secret
JWT_SECRET=$(openssl rand -base64 32)

echo ""
echo -e "${BLUE}=== Installing Dependencies ===${NC}"
echo ""

# Install dependencies
apt-get update
apt-get install -y \
    apt-transport-https \
    curl \
    wget \
    git \
    unzip \
    nginx \
    certbot \
    python3-certbot-nginx

# Install .NET 8
if ! command -v dotnet &> /dev/null; then
    echo -e "${BLUE}Installing .NET 8...${NC}"
    wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
    apt-get update
    apt-get install -y dotnet-sdk-8.0
fi

echo -e "${GREEN}.NET $(dotnet --version) installed${NC}"

# Create service user
if ! id "$SERVICE_USER" &>/dev/null; then
    echo -e "${BLUE}Creating service user...${NC}"
    useradd -r -s /bin/false -d $INSTALL_DIR $SERVICE_USER
fi

# Create directories
echo -e "${BLUE}Creating directories...${NC}"
mkdir -p $INSTALL_DIR
mkdir -p $INSTALL_DIR/data
mkdir -p $INSTALL_DIR/config
mkdir -p $INSTALL_DIR/data/logs
mkdir -p $INSTALL_DIR/data/backups

# Download/Build application
echo -e "${BLUE}Building application...${NC}"

# If running from git repo
if [ -f "XcluadeAgent.sln" ]; then
    dotnet publish src/XcluadeAgent.Api/XcluadeAgent.Api.csproj -c Release -o $INSTALL_DIR/app
else
    # Download from release (when available)
    echo -e "${YELLOW}Please build and deploy manually or set up from git${NC}"
fi

# Create configuration
echo -e "${BLUE}Creating configuration...${NC}"
cat > $INSTALL_DIR/config/config.yaml << EOF
# XcluadeAgent Configuration
# Generated by installer

app:
  name: XcluadeAgent
  version: 1.0.0

server:
  host: 0.0.0.0
  port: ${PORT}
  $([ -n "$DOMAIN" ] && echo "externalUrl: https://${DOMAIN}")

database:
  provider: sqlite
  connectionString: Data Source=${INSTALL_DIR}/data/xcluadeagent.db

github:
  accessToken: ${GITHUB_TOKEN}

security:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMinutes: 1440
  allowedOrigins:
    - http://localhost:${PORT}
    $([ -n "$DOMAIN" ] && echo "- https://${DOMAIN}")

ai:
  enabled: false
  mode: suggest
  primary:
    type: ollama
    endpoint: http://localhost:11434
    model: qwen2.5-coder:7b

backup:
  basePath: ${INSTALL_DIR}/data/backups
  defaultMaxBackups: 5

logging:
  level: Information
  path: ${INSTALL_DIR}/data/logs
  retentionDays: 30
EOF

# Set permissions
chown -R $SERVICE_USER:$SERVICE_USER $INSTALL_DIR
chmod 600 $INSTALL_DIR/config/config.yaml

# Create systemd service
echo -e "${BLUE}Creating systemd service...${NC}"
cat > /etc/systemd/system/${SERVICE_NAME}.service << EOF
[Unit]
Description=XcluadeAgent - GitHub Sync Service
Documentation=https://xman4289.com
After=network.target

[Service]
Type=notify
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}/app
ExecStart=/usr/bin/dotnet ${INSTALL_DIR}/app/XcluadeAgent.Api.dll
Restart=always
RestartSec=10
TimeoutStartSec=60
TimeoutStopSec=30

# Environment
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=ASPNETCORE_URLS=http://localhost:${PORT}
Environment=DOTNET_CLI_HOME=${INSTALL_DIR}

# Security
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${INSTALL_DIR}/data
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

# Setup Nginx reverse proxy
if [ -n "$DOMAIN" ]; then
    echo -e "${BLUE}Configuring Nginx...${NC}"
    cat > /etc/nginx/sites-available/${DOMAIN} << EOF
server {
    listen 80;
    server_name ${DOMAIN};

    location / {
        proxy_pass http://localhost:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF
    ln -sf /etc/nginx/sites-available/${DOMAIN} /etc/nginx/sites-enabled/
    nginx -t && systemctl reload nginx

    # Setup SSL
    if [ "$SETUP_SSL" = "y" ] || [ "$SETUP_SSL" = "Y" ]; then
        echo -e "${BLUE}Setting up SSL...${NC}"
        certbot --nginx -d ${DOMAIN} --non-interactive --agree-tos --email admin@${DOMAIN}
    fi
fi

# Open firewall
if command -v ufw &> /dev/null; then
    ufw allow ${PORT}/tcp
    ufw allow 'Nginx Full'
fi

# Enable and start service
echo -e "${BLUE}Starting service...${NC}"
systemctl daemon-reload
systemctl enable ${SERVICE_NAME}
systemctl start ${SERVICE_NAME}

# Wait for service to start
sleep 3

# Check status
if systemctl is-active --quiet ${SERVICE_NAME}; then
    echo -e "${GREEN}"
    echo "╔═══════════════════════════════════════════════════════════════════╗"
    echo "║                 Installation Complete!                             ║"
    echo "╚═══════════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo -e "${GREEN}XcluadeAgent is now running!${NC}"
    echo ""
    echo "Dashboard URL:"
    if [ -n "$DOMAIN" ]; then
        echo -e "  ${BLUE}https://${DOMAIN}${NC}"
    else
        echo -e "  ${BLUE}http://$(hostname -I | awk '{print $1}'):${PORT}${NC}"
    fi
    echo ""
    echo "Default login:"
    echo "  Username: admin"
    echo "  Password: admin123"
    echo ""
    echo -e "${YELLOW}⚠️  Please change the default password immediately!${NC}"
    echo ""
    echo "Useful commands:"
    echo "  sudo systemctl status ${SERVICE_NAME}   # Check status"
    echo "  sudo systemctl restart ${SERVICE_NAME}  # Restart"
    echo "  sudo journalctl -u ${SERVICE_NAME} -f   # View logs"
    echo ""
    echo "Configuration: ${INSTALL_DIR}/config/config.yaml"
    echo "Data: ${INSTALL_DIR}/data"
    echo ""
    echo -e "${GREEN}Developed by xman studio | https://xman4289.com${NC}"
else
    echo -e "${RED}Service failed to start. Check logs:${NC}"
    echo "  sudo journalctl -u ${SERVICE_NAME} -n 50"
fi
